### ISSUE TITLE
[BUG] `FsWorkbook.fromXlsxFile` throws IOException under unknown circumstances

### ISSUE THREAD

**Issue by omaus** [CSBiology/FsSpreadsheet#26]
**Describe the bug**
Some XLSX files let `FsWorkbook.fromXlsxFile` throw an IOException. The reason behind this (the properties of such files) are currently not known.

**To Reproduce**
1. Download this file: 
[errorInducing.xlsx](https://github.com/CSBiology/FsSpreadsheet/files/11367093/errorInducing.xlsx)
2. Use `FsWorkbook.fromXlsxFile <pathToThisFile>` in a script environment
3. See error:
![image](https://user-images.githubusercontent.com/47781170/235503300-c29e478b-b74b-4557-bf11-7c71ce6a2c1a.png)

**Expected behavior**
At least a more precise error message.
Cases like these suggest that a readonly version of the function (see #25) is urgently needed.

**Comment by HLWeil** [comment]
#37 
#40
