### ISSUE TITLE
[BUG] Worksheets have no rows when reading Xlsx file

### ISSUE THREAD

**Issue by omaus** [CSBiology/FsSpreadsheet#31]
**Describe the bug**
Worksheets have no rows when reading Xlsx file.

**To Reproduce**
Have an Xlsx file with some values in it.
```fsharp
let wb = FsWorkbook.fromXlsxFile filepath
let ws1 = FsWorkbook.getWorksheets wb |> Seq.head
ws1.Rows
```

**Expected behavior**
All FsRows are in place where they should be.

**Additional context**
The problem here is that you have to call `ws1.RescanRows()` before being able to access them. Maybe it would be best to have this called in the `FsWorkbook.fromXlsxFile` method? Or is there anything that would speak against it? @HLWeil

**Comment by HLWeil** [comment]
Hard agree. Noticed this too but forgot to create this issue.
