### ISSUE TITLE
[Feature Request] Refactor all mutable list properties (worksheets, tables) to ResizeArray

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/FsSpreadsheet#53]
Such as:

![image](https://github.com/CSBiology/FsSpreadsheet/assets/39732517/679dedb9-689d-4830-bfd9-3ce2c5a91404)

This should increase Fable compatibility

**Comment by omaus** [comment]
Looks good from my part but I wouldn't exclude that this might raise an error somewhere.

But I'd give it a go! ☺

**Comment by Freymaurer** [comment]
This is nearly done!
